version: '3.8'

services:
  postgres:
    image: postgres:13.0-alpine
    container_name: postgres
    restart: always

    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - /.env

    ports:
      - "5432:5432"
  auth-service:
    build: .
    container_name: auth-service
    restart: always
    depends_on:
      - postgres
    env_file:
      - /.env

    ports:
      - "8080:8080"


volumes:
  database:
  static: